//! Port of `internal/model/episodes.go` + `episodes_parser.go` — season/episode
//! extraction from a release name.
//!
//! ⚠️ **Parity over correctness.** The Go regex captures an *extra* outer group
//! per range token that `EpisodesMatchToEpisodes` does not account for, so the
//! group indices it reads are shifted by one. The observable consequences are
//! reproduced here verbatim (they are the frozen oracle — the classifier corpus
//! is generated by exactly this code):
//!
//! * `S01E01` → `S01` (the episode is dropped: the code's "has episodes" check
//!   reads the season-list slot, which is empty).
//! * `S01-03` → `S00-01` (`ParseInt("01-03")` errors → 0, and the range-end is
//!   read from the season-*start* group).
//! * `1x05` → `S00` (the x-format branch is dead code — group 1, the whole
//!   match, is always non-empty, so the "regular" branch always runs).
//!
//! Do NOT "fix" these; a fix would diverge from Go. Fixtures in
//! `testdata/parity/release/episodes.jsonl` lock the exact outputs.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt;
use std::sync::LazyLock;

use regex::Regex;

/// The anchored episodes regex, byte-identical to Go's `episodesRegex.String()`
/// after the ASCII adaptation (Go `\d`==`[0-9]`, `\s`==`[\t\n\f\r ]`; both are
/// Unicode in the Rust `regex` crate by default). Verified against the Go dump
/// in the crate tests.
const EPISODES_PATTERN: &str = r"^((?:(?:(?:(?:(?:[Ss][Ee][Aa][Ss][Oo][Nn]))|(?:(?:[Ss])))[\t\n\f\r ]?(([0-9]{1,2})(?:(?:[\t\n\f\r ]?\x2D[\t\n\f\r ]?(?:[sS]?[\t\n\f\r ]?)?([0-9]{1,2}))|(?:[\t\n\f\r ]?,[\t\n\f\r ]?(?:[sS]?[\t\n\f\r ]?)?([0-9]{1,2})[\t\n\f\r ]?)+)?)[\t\n\f\r ]?)(?:(?:(?:(?:[Ee][Pp][Ii][Ss][Oo][Dd][Ee]))|(?:(?:[Ee][Pp]))|(?:(?:[Ee])))[\t\n\f\r ]?(([0-9]{1,2})(?:(?:[\t\n\f\r ]?\x2D[\t\n\f\r ]?(?:[eE]?[\t\n\f\r ]?)?([0-9]{1,2}))|(?:[\t\n\f\r ]?,[\t\n\f\r ]?(?:[eE]?[\t\n\f\r ]?)?([0-9]{1,2})[\t\n\f\r ]?)+)?))?)|(?:(?:([0-9]{1,2})[xX]([0-9]{1,2}))(?:[\t\n\f\r ]?\x2D[\t\n\f\r ]?([0-9]{1,2}))?))$";

static EPISODES_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(EPISODES_PATTERN).expect("episodes regex compiles"));

/// Season/episode set — port of `model.Episodes` (`map[int]map[int]struct{}`).
/// A season maps to its episode set; an empty set means "whole season".
/// `BTreeMap`/`BTreeSet` give the sorted iteration Go achieves via explicit
/// `sort.Slice` in `SeasonEntries`.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Episodes {
    seasons: BTreeMap<i64, BTreeSet<i64>>,
}

impl Episodes {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn is_empty(&self) -> bool {
        self.seasons.is_empty()
    }

    /// `AddSeason` — records a whole season (resets any episodes, matching Go's
    /// `e[season] = make(map[int]struct{})`).
    pub fn add_season(&mut self, season: i64) {
        self.seasons.insert(season, BTreeSet::new());
    }

    /// `AddEpisode`.
    pub fn add_episode(&mut self, season: i64, episode: i64) {
        self.seasons.entry(season).or_default().insert(episode);
    }
}

impl fmt::Display for Episodes {
    /// Port of `Episodes.String()`.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // seasonEntries: sorted seasons (BTreeMap) with sorted episodes (BTreeSet).
        let whole_seasons: Vec<i64> = self
            .seasons
            .iter()
            .filter(|(_, eps)| eps.is_empty())
            .map(|(s, _)| *s)
            .collect();

        let mut parts_map: BTreeMap<i64, String> = BTreeMap::new();
        for r in contiguous_ranges(&whole_seasons) {
            parts_map.insert(r.start, format!("S{}", r));
        }
        for (season, eps) in &self.seasons {
            if !eps.is_empty() {
                parts_map.insert(*season, format_season(*season, eps));
            }
        }

        // Emit in season order, only seasons present in parts_map.
        let parts: Vec<String> = self
            .seasons
            .keys()
            .filter_map(|s| parts_map.get(s).cloned())
            .collect();

        write!(f, "{}", parts.join(", "))
    }
}

/// Port of `Season.String()` for a season that has episodes.
fn format_season(season: i64, episodes: &BTreeSet<i64>) -> String {
    let mut s = format!("S{season:02}");
    if !episodes.is_empty() {
        let eps: Vec<i64> = episodes.iter().copied().collect();
        let parts: Vec<String> = contiguous_ranges(&eps)
            .iter()
            .map(|r| format!("E{r}"))
            .collect();
        s.push_str(&parts.join(","));
    }
    s
}

struct ContiguousRange {
    start: i64,
    end: i64,
}

impl fmt::Display for ContiguousRange {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if self.start == self.end {
            write!(f, "{:02}", self.start)
        } else {
            write!(f, "{:02}-{:02}", self.start, self.end)
        }
    }
}

/// Port of `getContiguousRanges`. NOTE: like Go, an empty input yields a single
/// `{0,0}` range (Go appends the zero-value `currentRange` unconditionally).
fn contiguous_ranges(ordered: &[i64]) -> Vec<ContiguousRange> {
    let mut ranges = Vec::new();
    let mut current = ContiguousRange { start: 0, end: 0 };
    for (i, &v) in ordered.iter().enumerate() {
        if i == 0 {
            current = ContiguousRange { start: v, end: v };
            continue;
        }
        if v == current.end + 1 {
            current.end = v;
            continue;
        }
        ranges.push(current);
        current = ContiguousRange { start: v, end: v };
    }
    ranges.push(current);
    ranges
}

/// Go `strconv.ParseInt(s, 10, 16)` with the error ignored (returns 0). Real
/// digit groups are 1-2 chars; the "outer" groups the buggy indices read (e.g.
/// `"01-03"`, `"S01"`) fail to parse and become 0 — which is the bug's source.
fn parse_int(s: &str) -> i64 {
    s.parse::<i64>().unwrap_or(0)
}

/// Port of `EpisodesMatchToEpisodes`. `g` are the capture group strings with
/// `g[0]` the whole match (empty string for non-participating groups), exactly
/// as Go's `FindStringSubmatch` slice. The index choices are Go's — verbatim,
/// including the off-by-one bugs.
pub(crate) fn episodes_match_to_episodes(g: &[&str]) -> Episodes {
    let mut episodes = Episodes::new();
    if g.len() < 12 {
        return episodes;
    }

    if !g[1].is_empty() {
        // regular format
        let season_start = parse_int(g[2]);

        if g[5].is_empty() {
            // no episodes
            if !g[3].is_empty() {
                // a season range
                let season_end = parse_int(g[3]);
                let mut i = season_start;
                while i <= season_end {
                    episodes.add_season(i);
                    i += 1;
                }
            } else if !g[4].is_empty() {
                // a list of seasons
                for season in g[1].split(',') {
                    episodes.add_season(parse_int(season));
                }
            } else {
                // a single season
                episodes.add_season(season_start);
            }
        } else {
            // episodes
            let episode_start = parse_int(g[6]);
            if !g[7].is_empty() {
                // an episode range
                let episode_end = parse_int(g[7]);
                let mut i = episode_start;
                while i <= episode_end {
                    episodes.add_episode(season_start, i);
                    i += 1;
                }
            } else if !g[8].is_empty() {
                // a list of episodes
                for episode in g[5].split(',') {
                    episodes.add_episode(season_start, parse_int(episode));
                }
            } else {
                // a single episode
                episodes.add_episode(season_start, episode_start);
            }
        }
    } else {
        // x format (dead code in practice: g[1] is the whole match, never empty)
        let season = parse_int(g[9]);
        let episode_start = parse_int(g[10]);
        let mut episode_end = episode_start;
        if !g[11].is_empty() {
            episode_end = parse_int(g[11]);
        }
        let mut i = episode_start;
        while i <= episode_end {
            episodes.add_episode(season, i);
            i += 1;
        }
    }

    episodes
}

/// Port of `ParseEpisodes`.
pub fn parse_episodes(input: &str) -> Episodes {
    match EPISODES_RE.captures(input) {
        None => Episodes::new(),
        Some(caps) => {
            let groups: Vec<&str> = (0..caps.len())
                .map(|i| caps.get(i).map_or("", |m| m.as_str()))
                .collect();
            episodes_match_to_episodes(&groups)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testsupport::{adapt_go_pattern, load_go_patterns};

    #[test]
    fn episodes_pattern_matches_go() {
        let go = load_go_patterns();
        assert_eq!(EPISODES_PATTERN, adapt_go_pattern(&go["episodes"]));
        // And it compiles.
        LazyLock::force(&EPISODES_RE);
    }

    // Direct render tests — ports of Go's TestEpisodesString.
    fn ep(seasons: &[(i64, &[i64])]) -> Episodes {
        let mut e = Episodes::new();
        for (s, eps) in seasons {
            if eps.is_empty() {
                e.add_season(*s);
            } else {
                for &n in *eps {
                    e.add_episode(*s, n);
                }
            }
        }
        e
    }

    #[test]
    fn render_matches_go_unit_tests() {
        assert_eq!(ep(&[]).to_string(), "");
        assert_eq!(ep(&[(1, &[])]).to_string(), "S01");
        assert_eq!(ep(&[(1, &[]), (2, &[]), (3, &[])]).to_string(), "S01-03");
        assert_eq!(ep(&[(1, &[1, 2])]).to_string(), "S01E01-02");
        assert_eq!(ep(&[(1, &[1, 2]), (2, &[])]).to_string(), "S01E01-02, S02");
        assert_eq!(
            ep(&[
                (1, &[]),
                (2, &[]),
                (3, &[]),
                (5, &[1, 2, 4]),
                (6, &[]),
                (7, &[]),
                (9, &[]),
            ])
            .to_string(),
            "S01-03, S05E01-02,E04, S06-07, S09"
        );
    }
}
