//! Go-generated byte parity for the pure KRPC/compact codec boundary.

use std::fs::File;
use std::io::{BufRead, BufReader};
use std::path::Path;

use bitmagnet_dht::KrpcMessage;
use serde::Deserialize;

#[derive(Deserialize)]
struct Fixture {
    id: String,
    subsystem: String,
    input: serde_json::Value,
    expected: serde_json::Value,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct WireExpected {
    wire_hex: String,
    go_decoded: KrpcMessage,
    go_canonical_wire_hex: String,
    round_trip_stable: bool,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct CompatibilityInput {
    wire_hex: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct CompatibilityExpected {
    go_accepted: bool,
    rust_accepted: bool,
    #[serde(default)]
    go_canonical_wire_hex: String,
    #[serde(default)]
    rust_canonical_wire_hex: String,
    reason: String,
}

fn fixtures() -> Vec<Fixture> {
    let path =
        Path::new(env!("CARGO_MANIFEST_DIR")).join("../../../testdata/parity/dht/krpc_wire.jsonl");
    let file = File::open(&path).unwrap_or_else(|error| panic!("open {}: {error}", path.display()));
    BufReader::new(file)
        .lines()
        .map(|line| line.expect("read KRPC fixture line"))
        .filter(|line| !line.trim().is_empty())
        .map(|line| serde_json::from_str(&line).expect("decode KRPC fixture"))
        .collect()
}

#[test]
fn typed_krpc_messages_match_go_bytes_exactly() {
    let fixtures = fixtures();
    let typed = fixtures
        .iter()
        .filter(|fixture| !fixture.id.starts_with("compat_"))
        .collect::<Vec<_>>();
    assert_eq!(typed.len(), 13, "expected thirteen typed wire cases");

    for fixture in typed {
        assert_eq!(fixture.subsystem, "dht_krpc_wire");
        let message: KrpcMessage = serde_json::from_value(fixture.input.clone())
            .unwrap_or_else(|error| panic!("[{}] decode input: {error}", fixture.id));
        let expected: WireExpected = serde_json::from_value(fixture.expected.clone())
            .unwrap_or_else(|error| panic!("[{}] decode expected: {error}", fixture.id));
        let actual = message
            .encode()
            .unwrap_or_else(|error| panic!("[{}] encode: {error}", fixture.id));
        assert_eq!(hex::encode(&actual), expected.wire_hex, "[{}]", fixture.id);
        let decoded = KrpcMessage::decode(&actual)
            .unwrap_or_else(|error| panic!("[{}] decode Rust bytes: {error}", fixture.id));
        assert_eq!(
            decoded, expected.go_decoded,
            "[{}] Go decoded projection",
            fixture.id
        );
        assert_eq!(
            hex::encode(decoded.encode().expect("re-encode decoded message")),
            expected.go_canonical_wire_hex,
            "[{}] Go canonical re-encode",
            fixture.id
        );
        assert_eq!(
            expected.round_trip_stable,
            expected.wire_hex == expected.go_canonical_wire_hex,
            "[{}] Go round-trip stability flag",
            fixture.id
        );
    }
}

#[test]
fn syntax_compatibility_boundary_is_explicitly_gated() {
    let fixtures = fixtures();
    let compatibility = fixtures
        .iter()
        .filter(|fixture| fixture.id.starts_with("compat_"))
        .collect::<Vec<_>>();
    assert_eq!(
        compatibility.len(),
        13,
        "expected thirteen compatibility probes"
    );

    for fixture in compatibility {
        let input: CompatibilityInput = serde_json::from_value(fixture.input.clone())
            .unwrap_or_else(|error| panic!("[{}] decode input: {error}", fixture.id));
        let expected: CompatibilityExpected = serde_json::from_value(fixture.expected.clone())
            .unwrap_or_else(|error| panic!("[{}] decode expected: {error}", fixture.id));
        let bytes = hex::decode(&input.wire_hex).expect("fixture wire is hexadecimal");
        let decoded = KrpcMessage::decode(&bytes);
        assert_eq!(
            decoded.is_ok(),
            expected.rust_accepted,
            "[{}] {}",
            fixture.id,
            expected.reason
        );
        if let Ok(message) = decoded {
            assert_eq!(
                hex::encode(message.encode().expect("canonical Rust re-encode")),
                expected.rust_canonical_wire_hex,
                "[{}] {}",
                fixture.id,
                expected.reason
            );
            assert!(
                expected.go_accepted,
                "shared acceptance requires Go acceptance"
            );
            assert_eq!(
                expected.go_canonical_wire_hex, expected.rust_canonical_wire_hex,
                "[{}] shared canonical projection",
                fixture.id
            );
        }
    }
}
