//! Canonical JSON encoding, byte-compatible with Go's `tape.Marshal`.
//!
//! # Why bytes and not values
//!
//! [`crate::Session::next`] decides whether the replay is asking the recorded
//! question by comparing the request **byte for byte** against the recording —
//! Go's `equalJSON` does the same, and is allowed to because both sides come
//! from `tape.Marshal`. So a Rust port that encodes the same value differently
//! desyncs on every observation, even though nothing is semantically wrong.
//! This module exists to make that impossible.
//!
//! # What Go actually does
//!
//! `tape.Marshal` is `encoding/json` with `SetEscapeHTML(false)`. Its string
//! escaping was determined empirically against Go 1.24 rather than from
//! memory — see `testdata/go-canonical-escapes.json`, generated by
//! `TestCanonicalEscapeFixture` in `internal/tape`:
//!
//! | input            | Go output        | serde_json | agree |
//! |------------------|------------------|------------|-------|
//! | `<`, `>`, `&`    | literal          | literal    | ✅ (HTML escaping is off) |
//! | `/`              | literal          | literal    | ✅ |
//! | `\x08`, `\x0c`   | `\b`, `\f`       | `\b`, `\f` | ✅ |
//! | `\t \n \r`       | `\t \n \r`       | same       | ✅ |
//! | other `< 0x20`   | `\u00xx`         | `\u00xx`   | ✅ |
//! | `\x7f` (DEL)     | literal          | literal    | ✅ |
//! | non-ASCII        | literal UTF-8    | literal    | ✅ |
//! | **U+2028/U+2029**| **`\u2028`/`\u2029`** | **literal** | ❌ |
//!
//! Exactly one divergence, and it is the whole reason this module is not just
//! `serde_json::to_string`. Go escapes the Unicode line separators
//! unconditionally (a JSONP-era safety measure that `SetEscapeHTML(false)` does
//! not turn off); serde_json emits them raw. They are rare but entirely legal in
//! a torrent title, which is precisely the kind of input this tape carries.
//!
//! # Ordering
//!
//! Go orders struct fields by declaration and map keys by sort order. serde
//! serialises struct fields in declaration order too, and `serde_json::Map` is a
//! `BTreeMap` unless the `preserve_order` feature is on (it is not here), so
//! both orderings already agree. Do NOT round-trip a struct through
//! `serde_json::Value` to canonicalise it: that would turn declaration order
//! into sorted order and silently diverge from Go.

use serde::Serialize;
use serde_json::ser::{CharEscape, Formatter};

/// Serialise `value` exactly as Go's `tape.Marshal` would.
pub fn marshal<T: Serialize + ?Sized>(value: &T) -> Result<String, serde_json::Error> {
    let mut out = Vec::new();
    let mut ser = serde_json::Serializer::with_formatter(&mut out, GoFormatter);
    value.serialize(&mut ser)?;

    // Serializer output is UTF-8 by construction.
    Ok(String::from_utf8(out).expect("serde_json emits UTF-8"))
}

/// `serde_json` formatter matching Go's `encoding/json` with HTML escaping off.
///
/// Only string escaping is overridden; numbers, structure and key order already
/// agree (see the module docs).
#[derive(Clone, Copy, Debug)]
pub struct GoFormatter;

impl Formatter for GoFormatter {
    /// serde_json hands us the runs of characters it decided need no escaping.
    /// U+2028/U+2029 are in those runs — serde_json does not escape them and Go
    /// does — so this is where that single divergence is repaired.
    fn write_string_fragment<W>(&mut self, writer: &mut W, fragment: &str) -> std::io::Result<()>
    where
        W: ?Sized + std::io::Write,
    {
        let mut rest = fragment;

        while let Some(idx) = rest.find(['\u{2028}', '\u{2029}']) {
            writer.write_all(&rest.as_bytes()[..idx])?;

            // Both are three UTF-8 bytes and differ only in the last nibble,
            // which is how Go writes them (`\u202` + hex of c&0xF).
            let escape = if rest[idx..].starts_with('\u{2028}') {
                br"\u2028"
            } else {
                br"\u2029"
            };
            writer.write_all(escape)?;

            rest = &rest[idx + '\u{2028}'.len_utf8()..];
        }

        writer.write_all(rest.as_bytes())
    }

    /// Go and serde_json agree on every escape serde_json emits — including
    /// `\b` and `\f`, which Go does special-case (verified, not assumed). The
    /// default implementation is therefore already correct; it is spelled out
    /// here so the agreement is a recorded decision rather than an omission.
    fn write_char_escape<W>(
        &mut self,
        writer: &mut W,
        char_escape: CharEscape,
    ) -> std::io::Result<()>
    where
        W: ?Sized + std::io::Write,
    {
        use CharEscape::{
            AsciiControl, Backspace, CarriageReturn, FormFeed, LineFeed, Quote, ReverseSolidus,
            Solidus, Tab,
        };

        let bytes: &[u8] = match char_escape {
            Quote => br#"\""#,
            ReverseSolidus => br"\\",
            // Unreachable with serde_json's default escape logic, which never
            // asks for an escaped solidus — and Go does not escape `/` either
            // (verified). Spelled out so the match is exhaustive by intent
            // rather than by a catch-all that could mask a future variant.
            Solidus => br"\/",
            Backspace => br"\b",
            FormFeed => br"\f",
            LineFeed => br"\n",
            CarriageReturn => br"\r",
            Tab => br"\t",
            AsciiControl(byte) => {
                // Go writes lowercase hex: `\u00` + hex[b>>4] + hex[b&0xF].
                const HEX: &[u8; 16] = b"0123456789abcdef";
                let buf = [
                    b'\\',
                    b'u',
                    b'0',
                    b'0',
                    HEX[(byte >> 4) as usize],
                    HEX[(byte & 0xF) as usize],
                ];
                return writer.write_all(&buf);
            }
        };

        writer.write_all(bytes)
    }
}
