//! Disabled-by-default, bounded parity implementation of torrent tag mutations.

use std::collections::HashSet;
use std::str::FromStr;
use std::sync::Arc;

use async_graphql::{Error, Result};
use async_trait::async_trait;
use bitmagnet_db::PgPool;
use bitmagnet_model::InfoHash;
use thiserror::Error;

use super::scalars::Hash20;

/// Maximum hashes accepted by one mutation.
pub const MAX_TAG_MUTATION_INFO_HASHES: usize = 10_000;
/// Maximum tag-name arguments accepted by one non-no-op mutation.
pub const MAX_TAG_MUTATION_TAG_NAMES: usize = 1_000;
/// Maximum deduplicated rows generated by one put/set operation.
pub const MAX_TAG_MUTATION_ROWS: usize = 100_000;

const TAG_NAME_MAX_BYTES: usize = 30;

/// Normalized request for `torrent.putTags`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PutTagsRequest {
    /// Deduplicated hashes in caller order.
    pub info_hashes: Vec<InfoHash>,
    /// Validated and deduplicated tag names in caller order.
    pub tag_names: Vec<String>,
}

/// Normalized request for `torrent.setTags`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SetTagsRequest {
    /// Deduplicated hashes in caller order.
    pub info_hashes: Vec<InfoHash>,
    /// Validated and deduplicated desired tag names in caller order.
    pub tag_names: Vec<String>,
}

/// Normalized request for `torrent.deleteTags`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DeleteTagsRequest {
    /// Deduplicated optional hash filter.
    pub info_hashes: Vec<InfoHash>,
    /// Deduplicated optional name filter. Go intentionally does not validate it.
    pub tag_names: Vec<String>,
}

/// Typed failures from the torrent-tag mutation adapter.
#[derive(Debug, Error)]
pub enum TorrentTagMutationsError {
    /// The schema was built without the separately authenticated writer runtime.
    #[error("torrent tag mutations are disabled")]
    Disabled,
    /// The PostgreSQL mutation failed.
    #[error("torrent tag mutation PostgreSQL write failed: {0}")]
    Database(#[from] sqlx::Error),
}

/// Runtime seam for the three torrent-tag mutations.
#[async_trait]
pub trait TorrentTagMutationsRuntime: Send + Sync {
    /// Adds the Cartesian product of hashes and tag names without overwriting rows.
    async fn put_tags(
        &self,
        request: PutTagsRequest,
    ) -> std::result::Result<(), TorrentTagMutationsError>;

    /// Replaces the complete tag set for each selected hash atomically.
    async fn set_tags(
        &self,
        request: SetTagsRequest,
    ) -> std::result::Result<(), TorrentTagMutationsError>;

    /// Deletes rows matching the optional hash and name filters.
    async fn delete_tags(
        &self,
        request: DeleteTagsRequest,
    ) -> std::result::Result<(), TorrentTagMutationsError>;
}

struct DisabledTorrentTagMutationsRuntime;

#[async_trait]
impl TorrentTagMutationsRuntime for DisabledTorrentTagMutationsRuntime {
    async fn put_tags(
        &self,
        _request: PutTagsRequest,
    ) -> std::result::Result<(), TorrentTagMutationsError> {
        Err(TorrentTagMutationsError::Disabled)
    }

    async fn set_tags(
        &self,
        _request: SetTagsRequest,
    ) -> std::result::Result<(), TorrentTagMutationsError> {
        Err(TorrentTagMutationsError::Disabled)
    }

    async fn delete_tags(
        &self,
        _request: DeleteTagsRequest,
    ) -> std::result::Result<(), TorrentTagMutationsError> {
        Err(TorrentTagMutationsError::Disabled)
    }
}

/// PostgreSQL implementation backed by a caller-owned, separately authorized pool.
pub struct PgTorrentTagMutationsRuntime {
    pool: PgPool,
}

impl PgTorrentTagMutationsRuntime {
    /// Constructs the writer adapter.
    #[must_use]
    pub fn new(pool: PgPool) -> Self {
        Self { pool }
    }
}

#[async_trait]
impl TorrentTagMutationsRuntime for PgTorrentTagMutationsRuntime {
    async fn put_tags(
        &self,
        request: PutTagsRequest,
    ) -> std::result::Result<(), TorrentTagMutationsError> {
        if request.info_hashes.is_empty() || request.tag_names.is_empty() {
            return Ok(());
        }
        insert_tags(&self.pool, &request.info_hashes, &request.tag_names).await?;
        Ok(())
    }

    async fn set_tags(
        &self,
        request: SetTagsRequest,
    ) -> std::result::Result<(), TorrentTagMutationsError> {
        if request.info_hashes.is_empty() {
            return Ok(());
        }

        let hashes = hash_bytes(&request.info_hashes);
        let mut transaction = self.pool.begin().await?;
        sqlx::query(
            "DELETE FROM torrent_tags \
             WHERE info_hash = ANY($1::bytea[]) \
               AND (cardinality($2::text[]) = 0 OR NOT (name = ANY($2::text[])))",
        )
        .bind(&hashes)
        .bind(&request.tag_names)
        .execute(&mut *transaction)
        .await?;

        if !request.tag_names.is_empty() {
            insert_tags(&mut *transaction, &request.info_hashes, &request.tag_names).await?;
        }
        transaction.commit().await?;
        Ok(())
    }

    async fn delete_tags(
        &self,
        request: DeleteTagsRequest,
    ) -> std::result::Result<(), TorrentTagMutationsError> {
        let hashes = hash_bytes(&request.info_hashes);
        match (hashes.is_empty(), request.tag_names.is_empty()) {
            (true, true) => return Ok(()),
            (false, true) => {
                sqlx::query("DELETE FROM torrent_tags WHERE info_hash = ANY($1::bytea[])")
                    .bind(hashes)
                    .execute(&self.pool)
                    .await?;
            }
            (true, false) => {
                sqlx::query("DELETE FROM torrent_tags WHERE name = ANY($1::text[])")
                    .bind(request.tag_names)
                    .execute(&self.pool)
                    .await?;
            }
            (false, false) => {
                sqlx::query(
                    "DELETE FROM torrent_tags \
                     WHERE info_hash = ANY($1::bytea[]) AND name = ANY($2::text[])",
                )
                .bind(hashes)
                .bind(request.tag_names)
                .execute(&self.pool)
                .await?;
            }
        }
        Ok(())
    }
}

async fn insert_tags<'e, E>(
    executor: E,
    info_hashes: &[InfoHash],
    tag_names: &[String],
) -> std::result::Result<(), sqlx::Error>
where
    E: sqlx::Executor<'e, Database = sqlx::Postgres>,
{
    sqlx::query(
        "INSERT INTO torrent_tags (info_hash, name, created_at, updated_at) \
         SELECT hashes.info_hash, tags.name, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP \
         FROM unnest($1::bytea[]) AS hashes(info_hash) \
         CROSS JOIN unnest($2::text[]) AS tags(name) \
         ON CONFLICT DO NOTHING",
    )
    .bind(hash_bytes(info_hashes))
    .bind(tag_names)
    .execute(executor)
    .await?;
    Ok(())
}

fn hash_bytes(info_hashes: &[InfoHash]) -> Vec<Vec<u8>> {
    info_hashes
        .iter()
        .map(|info_hash| info_hash.as_slice().to_vec())
        .collect()
}

/// GraphQL context wrapper for the tag-mutation runtime.
#[derive(Clone)]
pub struct TorrentTagMutationsRuntimeData(Arc<dyn TorrentTagMutationsRuntime>);

impl TorrentTagMutationsRuntimeData {
    /// Wraps an enabled runtime.
    #[must_use]
    pub fn new(runtime: Arc<dyn TorrentTagMutationsRuntime>) -> Self {
        Self(runtime)
    }

    /// Constructs the default fail-loud runtime.
    #[must_use]
    pub fn disabled() -> Self {
        Self::new(Arc::new(DisabledTorrentTagMutationsRuntime))
    }

    /// Constructs the PostgreSQL writer runtime.
    #[must_use]
    pub fn pg(pool: PgPool) -> Self {
        Self::new(Arc::new(PgTorrentTagMutationsRuntime::new(pool)))
    }
}

pub(super) async fn resolve_put(
    runtime: &TorrentTagMutationsRuntimeData,
    info_hashes: Vec<Hash20>,
    tag_names: Vec<String>,
) -> Result<()> {
    let request = normalize_put(info_hashes, tag_names)?;
    runtime
        .0
        .put_tags(request)
        .await
        .map_err(|error| Error::new(error.to_string()))
}

pub(super) async fn resolve_set(
    runtime: &TorrentTagMutationsRuntimeData,
    info_hashes: Vec<Hash20>,
    tag_names: Vec<String>,
) -> Result<()> {
    let request = normalize_set(info_hashes, tag_names)?;
    runtime
        .0
        .set_tags(request)
        .await
        .map_err(|error| Error::new(error.to_string()))
}

pub(super) async fn resolve_delete(
    runtime: &TorrentTagMutationsRuntimeData,
    info_hashes: Option<Vec<Hash20>>,
    tag_names: Option<Vec<String>>,
) -> Result<()> {
    let request = normalize_delete(
        info_hashes.unwrap_or_default(),
        tag_names.unwrap_or_default(),
    )?;
    runtime
        .0
        .delete_tags(request)
        .await
        .map_err(|error| Error::new(error.to_string()))
}

fn normalize_put(info_hashes: Vec<Hash20>, tag_names: Vec<String>) -> Result<PutTagsRequest> {
    let info_hashes = normalize_hashes(info_hashes)?;
    if info_hashes.is_empty() || tag_names.is_empty() {
        return Ok(PutTagsRequest {
            info_hashes,
            tag_names: Vec::new(),
        });
    }
    let tag_names = normalize_validated_tags(tag_names)?;
    enforce_cartesian_bound(info_hashes.len(), tag_names.len())?;
    Ok(PutTagsRequest {
        info_hashes,
        tag_names,
    })
}

fn normalize_set(info_hashes: Vec<Hash20>, tag_names: Vec<String>) -> Result<SetTagsRequest> {
    let info_hashes = normalize_hashes(info_hashes)?;
    if info_hashes.is_empty() {
        return Ok(SetTagsRequest {
            info_hashes,
            tag_names: Vec::new(),
        });
    }
    let tag_names = normalize_validated_tags(tag_names)?;
    enforce_cartesian_bound(info_hashes.len(), tag_names.len())?;
    Ok(SetTagsRequest {
        info_hashes,
        tag_names,
    })
}

fn normalize_delete(info_hashes: Vec<Hash20>, tag_names: Vec<String>) -> Result<DeleteTagsRequest> {
    let info_hashes = normalize_hashes(info_hashes)?;
    if tag_names.len() > MAX_TAG_MUTATION_TAG_NAMES {
        return Err(Error::new(format!(
            "torrent.deleteTags tagNames has more than {MAX_TAG_MUTATION_TAG_NAMES} entries"
        )));
    }
    Ok(DeleteTagsRequest {
        info_hashes,
        tag_names: dedupe_strings(tag_names),
    })
}

fn normalize_hashes(raw: Vec<Hash20>) -> Result<Vec<InfoHash>> {
    if raw.len() > MAX_TAG_MUTATION_INFO_HASHES {
        return Err(Error::new(format!(
            "torrent tag mutation infoHashes has more than {MAX_TAG_MUTATION_INFO_HASHES} entries"
        )));
    }
    let mut seen = HashSet::with_capacity(raw.len());
    let mut normalized = Vec::with_capacity(raw.len());
    for Hash20(value) in raw {
        let info_hash = InfoHash::from_str(&value)
            .map_err(|error| Error::new(format!("invalid Hash20: {error}")))?;
        if seen.insert(info_hash) {
            normalized.push(info_hash);
        }
    }
    Ok(normalized)
}

fn normalize_validated_tags(tag_names: Vec<String>) -> Result<Vec<String>> {
    if tag_names.len() > MAX_TAG_MUTATION_TAG_NAMES {
        return Err(Error::new(format!(
            "torrent tag mutation tagNames has more than {MAX_TAG_MUTATION_TAG_NAMES} entries"
        )));
    }
    for tag_name in &tag_names {
        validate_tag_name(tag_name)?;
    }
    Ok(dedupe_strings(tag_names))
}

fn dedupe_strings(values: Vec<String>) -> Vec<String> {
    let mut seen = HashSet::with_capacity(values.len());
    values
        .into_iter()
        .filter(|value| seen.insert(value.clone()))
        .collect()
}

fn validate_tag_name(name: &str) -> Result<()> {
    let valid_kebab_case = !name.is_empty()
        && name.split('-').all(|part| {
            !part.is_empty()
                && part
                    .bytes()
                    .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit())
        });
    if !valid_kebab_case {
        return Err(Error::new(format!(
            "invalid tag name: '{name}' (must be kebab-case)"
        )));
    }
    if name.len() > TAG_NAME_MAX_BYTES {
        return Err(Error::new(format!(
            "invalid tag name: '{name}' (must be no longer than {TAG_NAME_MAX_BYTES} characters)"
        )));
    }
    Ok(())
}

fn enforce_cartesian_bound(info_hashes: usize, tag_names: usize) -> Result<()> {
    let rows = info_hashes.saturating_mul(tag_names);
    if rows > MAX_TAG_MUTATION_ROWS {
        return Err(Error::new(format!(
            "torrent tag mutation expands to more than {MAX_TAG_MUTATION_ROWS} rows"
        )));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use std::sync::Mutex;

    use async_graphql::{value, EmptySubscription};

    use super::*;
    use crate::schema::roots::{Mutation, Query};

    #[derive(Debug, Clone, PartialEq, Eq)]
    enum Call {
        Put(PutTagsRequest),
        Set(SetTagsRequest),
        Delete(DeleteTagsRequest),
    }

    struct FakeRuntime {
        calls: Arc<Mutex<Vec<Call>>>,
    }

    #[async_trait]
    impl TorrentTagMutationsRuntime for FakeRuntime {
        async fn put_tags(
            &self,
            request: PutTagsRequest,
        ) -> std::result::Result<(), TorrentTagMutationsError> {
            self.calls
                .lock()
                .expect("calls lock")
                .push(Call::Put(request));
            Ok(())
        }

        async fn set_tags(
            &self,
            request: SetTagsRequest,
        ) -> std::result::Result<(), TorrentTagMutationsError> {
            self.calls
                .lock()
                .expect("calls lock")
                .push(Call::Set(request));
            Ok(())
        }

        async fn delete_tags(
            &self,
            request: DeleteTagsRequest,
        ) -> std::result::Result<(), TorrentTagMutationsError> {
            self.calls
                .lock()
                .expect("calls lock")
                .push(Call::Delete(request));
            Ok(())
        }
    }

    fn schema_with_fake(calls: Arc<Mutex<Vec<Call>>>) -> crate::schema::Schema {
        let runtime: Arc<dyn TorrentTagMutationsRuntime> = Arc::new(FakeRuntime { calls });
        async_graphql::Schema::build(Query, Mutation, EmptySubscription)
            .data(TorrentTagMutationsRuntimeData::new(runtime))
            .finish()
    }

    fn hash(raw: &str) -> InfoHash {
        raw.parse().expect("test hash")
    }

    #[tokio::test]
    async fn graphql_mutations_normalize_calls_and_return_void() {
        let calls = Arc::new(Mutex::new(Vec::new()));
        let schema = schema_with_fake(Arc::clone(&calls));
        let first = "0123456789abcdef0123456789abcdef01234567";
        let second = "1111111111111111111111111111111111111111";

        let put = schema
            .execute(format!(
                "mutation {{ torrent {{ putTags(infoHashes: [\"{first}\", \"{first}\"], tagNames: [\"trusted\", \"trusted\"]) }} }}"
            ))
            .await;
        assert!(put.errors.is_empty(), "errors: {:?}", put.errors);
        assert_eq!(put.data, value!({ "torrent": { "putTags": null } }));

        let set = schema
            .execute(format!(
                "mutation {{ torrent {{ setTags(infoHashes: [\"{second}\"], tagNames: []) }} }}"
            ))
            .await;
        assert!(set.errors.is_empty(), "errors: {:?}", set.errors);

        let delete = schema
            .execute(
                "mutation { torrent { deleteTags(tagNames: [\"Not-Kebab\", \"Not-Kebab\"]) } }",
            )
            .await;
        assert!(delete.errors.is_empty(), "errors: {:?}", delete.errors);

        assert_eq!(
            *calls.lock().expect("calls lock"),
            vec![
                Call::Put(PutTagsRequest {
                    info_hashes: vec![hash(first)],
                    tag_names: vec!["trusted".to_owned()],
                }),
                Call::Set(SetTagsRequest {
                    info_hashes: vec![hash(second)],
                    tag_names: Vec::new(),
                }),
                Call::Delete(DeleteTagsRequest {
                    info_hashes: Vec::new(),
                    tag_names: vec!["Not-Kebab".to_owned()],
                }),
            ]
        );
    }

    #[test]
    fn validation_matches_go_and_no_op_short_circuits_tag_validation() {
        for valid in ["a", "tag-1", "a0-b9", &"a".repeat(TAG_NAME_MAX_BYTES)] {
            validate_tag_name(valid).expect("valid Go tag name");
        }
        for invalid in ["", "Upper", "a_b", "-a", "a-", "a--b", "é"] {
            assert!(validate_tag_name(invalid).is_err(), "accepted {invalid:?}");
        }
        assert!(validate_tag_name(&"a".repeat(TAG_NAME_MAX_BYTES + 1)).is_err());

        normalize_put(Vec::new(), vec!["Not-Kebab".to_owned()])
            .expect("Go put no-op skips tag validation");
        normalize_set(Vec::new(), vec!["Not-Kebab".to_owned()])
            .expect("Go set no-op skips tag validation");
        normalize_delete(Vec::new(), vec!["Not-Kebab".to_owned()])
            .expect("Go delete never validates tag filters");
    }

    #[test]
    fn invalid_hash_and_cartesian_bomb_fail_closed() {
        let invalid = normalize_put(
            vec![Hash20("not-a-hash".to_owned())],
            vec!["trusted".to_owned()],
        )
        .expect_err("invalid GraphQL hash must fail");
        assert!(invalid.message.contains("invalid Hash20"));

        let hashes = (0..=MAX_TAG_MUTATION_ROWS / 1_000)
            .map(|value| Hash20(format!("{value:040x}")))
            .collect();
        let tags = (0..1_000).map(|value| format!("tag-{value}")).collect();
        let error = normalize_put(hashes, tags).expect_err("Cartesian expansion must be bounded");
        assert!(error.message.contains("expands to more than"));
    }
}
