package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"

	"github.com/bitmagnet-io/bitmagnet/internal/gql"
	"github.com/bitmagnet-io/bitmagnet/internal/gql/gqlmodel"
	"github.com/bitmagnet-io/bitmagnet/internal/search/filesearch"
)

// TorrentContent is the resolver for the torrentContent field.
func (r *fileSearchItemResolver) TorrentContent(ctx context.Context, obj *filesearch.FileSearchItem) (gqlmodel.TorrentContent, error) {
	return gqlmodel.NewTorrentContentFromResultItem(obj.TorrentContent), nil
}

// FileSearchItem returns gql.FileSearchItemResolver implementation.
func (r *Resolver) FileSearchItem() gql.FileSearchItemResolver { return &fileSearchItemResolver{r} }

type fileSearchItemResolver struct{ *Resolver }
