package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"

	"github.com/bitmagnet-io/bitmagnet/internal/gql"
	"github.com/bitmagnet-io/bitmagnet/internal/gql/gqlmodel"
	"github.com/bitmagnet-io/bitmagnet/internal/model"
)

// OriginalLanguage is the resolver for the originalLanguage field.
func (r *contentResolver) OriginalLanguage(ctx context.Context, obj *model.Content) (*model.Language, error) {
	var language *model.Language
	if obj.OriginalLanguage.Valid {
		language = &obj.OriginalLanguage.Language
	}

	return language, nil
}

// FileExtensions is the resolver for the fileExtensions field.
//
// It mirrors the extension facet and the Tantivy document builder
// (internal/search/tantivy fileExtensionsForDoc): a single-file torrent has no
// per-file rows, so its extension is derived from the torrent name; multi-file
// torrents use the denormalised file_extensions JSONB column (the FileExts model
// field), which is populated at crawl time and is what search preloads (the Files
// relation is not). Binding straight to the column returned an empty list for
// single-file torrents even though the facet counts them by their name-derived
// extension.
func (r *torrentResolver) FileExtensions(ctx context.Context, obj *model.Torrent) ([]string, error) {
	if obj.SingleFile() {
		if ext := model.FileExtensionFromPath(obj.Name); ext.Valid {
			return []string{ext.String}, nil
		}

		return []string{}, nil
	}

	return obj.FileExts, nil
}

// Sources is the resolver for the sources field.
func (r *torrentResolver) Sources(ctx context.Context, obj *model.Torrent) ([]gqlmodel.TorrentSourceInfo, error) {
	return gqlmodel.TorrentSourceInfosFromTorrent(*obj), nil
}

// Content returns gql.ContentResolver implementation.
func (r *Resolver) Content() gql.ContentResolver { return &contentResolver{r} }

// Torrent returns gql.TorrentResolver implementation.
func (r *Resolver) Torrent() gql.TorrentResolver { return &torrentResolver{r} }

type contentResolver struct{ *Resolver }
type torrentResolver struct{ *Resolver }
