//! Behavioral parity: replay the frozen release-name fixtures and assert the
//! Rust video parsers produce Go-identical output.
//!
//! Oracle: `testdata/parity/release/video_attributes.jsonl`, generated by
//! running Go's `InferVideoResolution` / `InferVideoSource` /
//! `InferVideoCodecAndReleaseGroup` over each name (see the Lane R report). Each
//! fixture pins the exact enum `String()` (or null) Go returned.

use bitmagnet_release::{
    infer_video_codec_and_release_group, infer_video_resolution, infer_video_source,
};
use serde::Deserialize;

#[derive(Deserialize)]
struct VideoFixture {
    id: String,
    name: String,
    video_resolution: Option<String>,
    video_source: Option<String>,
    video_codec: Option<String>,
    release_group: Option<String>,
}

fn fixtures() -> Vec<VideoFixture> {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../../testdata/parity/release/video_attributes.jsonl"
    );
    let raw = std::fs::read_to_string(path).expect("read video_attributes.jsonl");
    raw.lines()
        .filter(|l| !l.trim().is_empty())
        .map(|l| serde_json::from_str(l).expect("valid fixture json"))
        .collect()
}

#[test]
fn video_attributes_match_go() {
    let fixtures = fixtures();
    assert!(fixtures.len() >= 70, "expected the full fixture corpus");

    for f in &fixtures {
        let res = infer_video_resolution(&f.name).map(|v| v.as_str().to_string());
        assert_eq!(res, f.video_resolution, "resolution mismatch for {}", f.id);

        let src = infer_video_source(&f.name).map(|v| v.as_str().to_string());
        assert_eq!(src, f.video_source, "source mismatch for {}", f.id);

        let (codec, rg) = infer_video_codec_and_release_group(&f.name);
        let codec = codec.map(|v| v.as_str().to_string());
        assert_eq!(codec, f.video_codec, "codec mismatch for {}", f.id);
        assert_eq!(rg, f.release_group, "release_group mismatch for {}", f.id);
    }
}
