[package]
name = "bitmagnet-search-query"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
bitmagnet-db = { path = "../bitmagnet-db" }
bitmagnet-model = { path = "../bitmagnet-model" }
sqlx = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
