query TorrentContentSearch(
  $cached: Boolean
  $hasNextPage: Boolean
  $limit: Int
  $orderBy: [TorrentContentOrderByInput!]
  $page: Int
  $queryString: String
  $totalCount: Boolean
) {
  torrentContent {
    search(
      input: {
        cached: $cached
        hasNextPage: $hasNextPage
        limit: $limit
        orderBy: $orderBy
        page: $page
        queryString: $queryString
        totalCount: $totalCount
      }
    ) {
      totalCount
      totalCountIsEstimate
      hasNextPage
      items {
        infoHash
        title
        seeders
        leechers
        publishedAt
        torrent {
          magnetUri
          name
          size
        }
      }
    }
  }
}
