package dhtcrawlerhealthcheck

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/bitmagnet-io/bitmagnet/internal/concurrency"
	"github.com/bitmagnet-io/bitmagnet/internal/protocol/dht/server"
)

var updateDHTHealthParity = flag.Bool(
	"update-dht-health-parity",
	false,
	"rewrite the Rust DHT health parity fixture",
)

const dhtHealthGoldenSHA256 = "284239c832efdffab12ab1971687e55363dceb9032a4f3a2ec546b8524813f18"

var dhtHealthFixtureIDs = [...]string{
	"inactive_ignores_stale_success",
	"zero_start_is_up",
	"initial_just_before_30_seconds",
	"initial_exactly_30_seconds",
	"successful_exactly_60_seconds",
	"successful_after_60_seconds",
	"last_response_ignored_without_success",
}

type dhtHealthFixture struct {
	ID        string            `json:"id"`
	Subsystem string            `json:"subsystem"`
	Oracle    dhtHealthOracle   `json:"oracle"`
	Input     dhtHealthInput    `json:"input"`
	Expected  dhtHealthExpected `json:"expected"`
}

type dhtHealthOracle struct {
	Implementation          string `json:"implementation"`
	Clock                   string `json:"clock"`
	LastResponseIsEvaluated bool   `json:"lastResponseIsEvaluated"`
}

type dhtHealthInput struct {
	Active               bool   `json:"active"`
	StartAgeNanos        *int64 `json:"startAgeNanos"`
	LastResponseAgeNanos *int64 `json:"lastResponseAgeNanos"`
	LastSuccessAgeNanos  *int64 `json:"lastSuccessAgeNanos"`
}

type dhtHealthExpected struct {
	Classification string `json:"classification"`
	ErrorMessage   string `json:"errorMessage"`
}

func TestGenerateDHTHealthParity(t *testing.T) {
	fixtures := generateDHTHealthFixtures(t)
	if len(fixtures) != len(dhtHealthFixtureIDs) {
		t.Fatalf("fixture count = %d, want %d", len(fixtures), len(dhtHealthFixtureIDs))
	}
	for index, fixture := range fixtures {
		if fixture.ID != dhtHealthFixtureIDs[index] || fixture.Subsystem != "dht_health" {
			t.Fatalf("unstable DHT health fixture %d: %#v", index, fixture)
		}
	}
	reconcileDHTHealthFixture(t, fixtures)
}

func generateDHTHealthFixtures(t *testing.T) []dhtHealthFixture {
	t.Helper()
	second := int64(time.Second)
	minute := int64(time.Minute)
	return []dhtHealthFixture{
		generateDHTHealthFixture(t, "inactive_ignores_stale_success", false, pointer(2*minute), nil, pointer(minute+1)),
		generateDHTHealthFixture(t, "zero_start_is_up", true, nil, nil, nil),
		generateDHTHealthFixture(t, "initial_just_before_30_seconds", true, pointer(30*second-1), nil, nil),
		generateDHTHealthFixture(t, "initial_exactly_30_seconds", true, pointer(30*second), nil, nil),
		generateDHTHealthFixture(t, "successful_exactly_60_seconds", true, pointer(2*minute), pointer(1), pointer(minute)),
		generateDHTHealthFixture(t, "successful_after_60_seconds", true, pointer(2*minute), pointer(1), pointer(minute+1)),
		generateDHTHealthFixture(t, "last_response_ignored_without_success", true, pointer(30*second), pointer(1), nil),
	}
}

func generateDHTHealthFixture(
	t *testing.T,
	id string,
	active bool,
	startAgeNanos *int64,
	lastResponseAgeNanos *int64,
	lastSuccessAgeNanos *int64,
) dhtHealthFixture {
	t.Helper()
	now := time.Unix(1_700_000_000, 0).UTC()
	lr := server.LastResponses{
		StartTime:    timeAtAge(now, startAgeNanos),
		LastResponse: timeAtAge(now, lastResponseAgeNanos),
		LastSuccess:  timeAtAge(now, lastSuccessAgeNanos),
	}
	activeValue := &concurrency.AtomicValue[bool]{}
	activeValue.Set(active)
	lastResponses := &concurrency.AtomicValue[server.LastResponses]{}
	lastResponses.Set(lr)
	check := NewCheck(activeValue, lastResponses)

	classification := "inactive"
	errorMessage := ""
	if check.IsActive() {
		classification = "up"
		if err := checkLastResponsesAt(now, lastResponses.Get()); err != nil {
			classification = "down"
			errorMessage = err.Error()
		}
	}

	return dhtHealthFixture{
		ID: id, Subsystem: "dht_health",
		Oracle: dhtHealthOracle{
			Implementation:          "production NewCheck activity and checkLastResponsesAt threshold policy",
			Clock:                   "fixed UTC instant with exact age vectors; no sleeps",
			LastResponseIsEvaluated: false,
		},
		Input: dhtHealthInput{
			Active: active, StartAgeNanos: startAgeNanos,
			LastResponseAgeNanos: lastResponseAgeNanos,
			LastSuccessAgeNanos:  lastSuccessAgeNanos,
		},
		Expected: dhtHealthExpected{
			Classification: classification,
			ErrorMessage:   errorMessage,
		},
	}
}

func timeAtAge(now time.Time, ageNanos *int64) time.Time {
	if ageNanos == nil {
		return time.Time{}
	}
	return now.Add(-time.Duration(*ageNanos))
}

func pointer(value int64) *int64 {
	return &value
}

func reconcileDHTHealthFixture(t *testing.T, fixtures []dhtHealthFixture) {
	t.Helper()
	var generated bytes.Buffer
	encoder := json.NewEncoder(&generated)
	encoder.SetEscapeHTML(false)
	for _, fixture := range fixtures {
		if err := encoder.Encode(fixture); err != nil {
			t.Fatal(err)
		}
	}
	generatedBytes := generated.Bytes()
	path := filepath.Join("..", "..", "..", "testdata", "parity", "dht", "health.jsonl")
	if *updateDHTHealthParity {
		if err := os.WriteFile(path, generatedBytes, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	digest := sha256.Sum256(generatedBytes)
	if digestHex := hex.EncodeToString(digest[:]); dhtHealthGoldenSHA256 != "TODO" && digestHex != dhtHealthGoldenSHA256 {
		t.Fatalf("generated DHT health fixture digest = %s, want %s", digestHex, dhtHealthGoldenSHA256)
	}
	checked, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read DHT health fixture; rerun with -update-dht-health-parity: %v", err)
	}
	if !bytes.Equal(checked, generatedBytes) {
		t.Fatal("DHT health fixture is stale; rerun with -update-dht-health-parity")
	}
}
