// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.28.3
// source: bitmagnet/file_search.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FileSearchService_SearchFiles_FullMethodName = "/bitmagnet.v1.FileSearchService/SearchFiles"
	FileSearchService_CountFiles_FullMethodName  = "/bitmagnet.v1.FileSearchService/CountFiles"
	FileSearchService_Facets_FullMethodName      = "/bitmagnet.v1.FileSearchService/Facets"
	FileSearchService_Reload_FullMethodName      = "/bitmagnet.v1.FileSearchService/Reload"
	FileSearchService_HealthCheck_FullMethodName = "/bitmagnet.v1.FileSearchService/HealthCheck"
)

// FileSearchServiceClient is the client API for FileSearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileSearchServiceClient interface {
	SearchFiles(ctx context.Context, in *SearchFilesRequest, opts ...grpc.CallOption) (*SearchFilesResponse, error)
	CountFiles(ctx context.Context, in *CountFilesRequest, opts ...grpc.CallOption) (*CountFilesResponse, error)
	Facets(ctx context.Context, in *FacetsRequest, opts ...grpc.CallOption) (*FacetsResponse, error)
	Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*ReloadResponse, error)
	HealthCheck(ctx context.Context, in *FileHealthCheckRequest, opts ...grpc.CallOption) (*FileHealthCheckResponse, error)
}

type fileSearchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileSearchServiceClient(cc grpc.ClientConnInterface) FileSearchServiceClient {
	return &fileSearchServiceClient{cc}
}

func (c *fileSearchServiceClient) SearchFiles(ctx context.Context, in *SearchFilesRequest, opts ...grpc.CallOption) (*SearchFilesResponse, error) {
	out := new(SearchFilesResponse)
	err := c.cc.Invoke(ctx, FileSearchService_SearchFiles_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileSearchServiceClient) CountFiles(ctx context.Context, in *CountFilesRequest, opts ...grpc.CallOption) (*CountFilesResponse, error) {
	out := new(CountFilesResponse)
	err := c.cc.Invoke(ctx, FileSearchService_CountFiles_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileSearchServiceClient) Facets(ctx context.Context, in *FacetsRequest, opts ...grpc.CallOption) (*FacetsResponse, error) {
	out := new(FacetsResponse)
	err := c.cc.Invoke(ctx, FileSearchService_Facets_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileSearchServiceClient) Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*ReloadResponse, error) {
	out := new(ReloadResponse)
	err := c.cc.Invoke(ctx, FileSearchService_Reload_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileSearchServiceClient) HealthCheck(ctx context.Context, in *FileHealthCheckRequest, opts ...grpc.CallOption) (*FileHealthCheckResponse, error) {
	out := new(FileHealthCheckResponse)
	err := c.cc.Invoke(ctx, FileSearchService_HealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileSearchServiceServer is the server API for FileSearchService service.
// All implementations must embed UnimplementedFileSearchServiceServer
// for forward compatibility
type FileSearchServiceServer interface {
	SearchFiles(context.Context, *SearchFilesRequest) (*SearchFilesResponse, error)
	CountFiles(context.Context, *CountFilesRequest) (*CountFilesResponse, error)
	Facets(context.Context, *FacetsRequest) (*FacetsResponse, error)
	Reload(context.Context, *ReloadRequest) (*ReloadResponse, error)
	HealthCheck(context.Context, *FileHealthCheckRequest) (*FileHealthCheckResponse, error)
	mustEmbedUnimplementedFileSearchServiceServer()
}

// UnimplementedFileSearchServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFileSearchServiceServer struct {
}

func (UnimplementedFileSearchServiceServer) SearchFiles(context.Context, *SearchFilesRequest) (*SearchFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchFiles not implemented")
}
func (UnimplementedFileSearchServiceServer) CountFiles(context.Context, *CountFilesRequest) (*CountFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountFiles not implemented")
}
func (UnimplementedFileSearchServiceServer) Facets(context.Context, *FacetsRequest) (*FacetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Facets not implemented")
}
func (UnimplementedFileSearchServiceServer) Reload(context.Context, *ReloadRequest) (*ReloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reload not implemented")
}
func (UnimplementedFileSearchServiceServer) HealthCheck(context.Context, *FileHealthCheckRequest) (*FileHealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedFileSearchServiceServer) mustEmbedUnimplementedFileSearchServiceServer() {}

// UnsafeFileSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileSearchServiceServer will
// result in compilation errors.
type UnsafeFileSearchServiceServer interface {
	mustEmbedUnimplementedFileSearchServiceServer()
}

func RegisterFileSearchServiceServer(s grpc.ServiceRegistrar, srv FileSearchServiceServer) {
	s.RegisterService(&FileSearchService_ServiceDesc, srv)
}

func _FileSearchService_SearchFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileSearchServiceServer).SearchFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileSearchService_SearchFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileSearchServiceServer).SearchFiles(ctx, req.(*SearchFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileSearchService_CountFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileSearchServiceServer).CountFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileSearchService_CountFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileSearchServiceServer).CountFiles(ctx, req.(*CountFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileSearchService_Facets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FacetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileSearchServiceServer).Facets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileSearchService_Facets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileSearchServiceServer).Facets(ctx, req.(*FacetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileSearchService_Reload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileSearchServiceServer).Reload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileSearchService_Reload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileSearchServiceServer).Reload(ctx, req.(*ReloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileSearchService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileHealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileSearchServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileSearchService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileSearchServiceServer).HealthCheck(ctx, req.(*FileHealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileSearchService_ServiceDesc is the grpc.ServiceDesc for FileSearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileSearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bitmagnet.v1.FileSearchService",
	HandlerType: (*FileSearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchFiles",
			Handler:    _FileSearchService_SearchFiles_Handler,
		},
		{
			MethodName: "CountFiles",
			Handler:    _FileSearchService_CountFiles_Handler,
		},
		{
			MethodName: "Facets",
			Handler:    _FileSearchService_Facets_Handler,
		},
		{
			MethodName: "Reload",
			Handler:    _FileSearchService_Reload_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _FileSearchService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bitmagnet/file_search.proto",
}
