// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.21.12
// source: bitmagnet/path_search.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PathSearchHealth_ServingStatus int32

const (
	PathSearchHealth_SERVING_STATUS_UNKNOWN     PathSearchHealth_ServingStatus = 0
	PathSearchHealth_SERVING_STATUS_SERVING     PathSearchHealth_ServingStatus = 1
	PathSearchHealth_SERVING_STATUS_NOT_SERVING PathSearchHealth_ServingStatus = 2
)

// Enum value maps for PathSearchHealth_ServingStatus.
var (
	PathSearchHealth_ServingStatus_name = map[int32]string{
		0: "SERVING_STATUS_UNKNOWN",
		1: "SERVING_STATUS_SERVING",
		2: "SERVING_STATUS_NOT_SERVING",
	}
	PathSearchHealth_ServingStatus_value = map[string]int32{
		"SERVING_STATUS_UNKNOWN":     0,
		"SERVING_STATUS_SERVING":     1,
		"SERVING_STATUS_NOT_SERVING": 2,
	}
)

func (x PathSearchHealth_ServingStatus) Enum() *PathSearchHealth_ServingStatus {
	p := new(PathSearchHealth_ServingStatus)
	*p = x
	return p
}

func (x PathSearchHealth_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PathSearchHealth_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_bitmagnet_path_search_proto_enumTypes[0].Descriptor()
}

func (PathSearchHealth_ServingStatus) Type() protoreflect.EnumType {
	return &file_bitmagnet_path_search_proto_enumTypes[0]
}

func (x PathSearchHealth_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PathSearchHealth_ServingStatus.Descriptor instead.
func (PathSearchHealth_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_bitmagnet_path_search_proto_rawDescGZIP(), []int{6, 0}
}

type PathCandidatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Path substring / free text, tokenized by the path ngram analyzer.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Final candidate page size. The server clamps this to a bounded maximum.
	Limit uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Extra candidates to return for backend exact-refine headroom. A zero value
	// uses the server default.
	Oversample uint32 `protobuf:"varint,3,opt,name=oversample,proto3" json:"oversample,omitempty"`
	// First recognized sort wins. Supported fields: seeders, size, files_count,
	// published_at. Unknown or empty sort uses relevance score.
	//
	// NOTE: "seeders" sort is INERT until seeders are denormalized into the index
	// (every doc currently indexes seeders=0); the backend re-ranks candidates by
	// fresh swarm seeders after hydration, so it must not rely on L3 seeder order.
	Sort []*SortBy `protobuf:"bytes,4,rep,name=sort,proto3" json:"sort,omitempty"`
}

func (x *PathCandidatesRequest) Reset() {
	*x = PathCandidatesRequest{}
	mi := &file_bitmagnet_path_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathCandidatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathCandidatesRequest) ProtoMessage() {}

func (x *PathCandidatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bitmagnet_path_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathCandidatesRequest.ProtoReflect.Descriptor instead.
func (*PathCandidatesRequest) Descriptor() ([]byte, []int) {
	return file_bitmagnet_path_search_proto_rawDescGZIP(), []int{0}
}

func (x *PathCandidatesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *PathCandidatesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PathCandidatesRequest) GetOversample() uint32 {
	if x != nil {
		return x.Oversample
	}
	return 0
}

func (x *PathCandidatesRequest) GetSort() []*SortBy {
	if x != nil {
		return x.Sort
	}
	return nil
}

type PathCandidate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 20-byte BitTorrent v1 info hash.
	InfoHash []byte `protobuf:"bytes,1,opt,name=info_hash,json=infoHash,proto3" json:"info_hash,omitempty"`
	// Tantivy relevance score. Zero when ordered only by a fast field.
	Score float32 `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	// The selected sort value when sorted by a fast field. Zero otherwise.
	SortValue uint64 `protobuf:"varint,3,opt,name=sort_value,json=sortValue,proto3" json:"sort_value,omitempty"`
}

func (x *PathCandidate) Reset() {
	*x = PathCandidate{}
	mi := &file_bitmagnet_path_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathCandidate) ProtoMessage() {}

func (x *PathCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_bitmagnet_path_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathCandidate.ProtoReflect.Descriptor instead.
func (*PathCandidate) Descriptor() ([]byte, []int) {
	return file_bitmagnet_path_search_proto_rawDescGZIP(), []int{1}
}

func (x *PathCandidate) GetInfoHash() []byte {
	if x != nil {
		return x.InfoHash
	}
	return nil
}

func (x *PathCandidate) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *PathCandidate) GetSortValue() uint64 {
	if x != nil {
		return x.SortValue
	}
	return 0
}

type PathCandidatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Candidates []*PathCandidate `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	// Torrent-doc candidate count, not an exact matching-file count.
	CandidateTotal uint64 `protobuf:"varint,2,opt,name=candidate_total,json=candidateTotal,proto3" json:"candidate_total,omitempty"`
	// Always true for this service: exact global file counts belong to L2/cache.
	Estimated bool `protobuf:"varint,3,opt,name=estimated,proto3" json:"estimated,omitempty"`
}

func (x *PathCandidatesResponse) Reset() {
	*x = PathCandidatesResponse{}
	mi := &file_bitmagnet_path_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathCandidatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathCandidatesResponse) ProtoMessage() {}

func (x *PathCandidatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bitmagnet_path_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathCandidatesResponse.ProtoReflect.Descriptor instead.
func (*PathCandidatesResponse) Descriptor() ([]byte, []int) {
	return file_bitmagnet_path_search_proto_rawDescGZIP(), []int{2}
}

func (x *PathCandidatesResponse) GetCandidates() []*PathCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *PathCandidatesResponse) GetCandidateTotal() uint64 {
	if x != nil {
		return x.CandidateTotal
	}
	return 0
}

func (x *PathCandidatesResponse) GetEstimated() bool {
	if x != nil {
		return x.Estimated
	}
	return false
}

type SuggestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// User-typed prefix. Server trims + lowercases + validates (min 2 chars
	// post-trim); a shorter prefix returns an empty response (never a full scan).
	Prefix string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// Max suggestions (top-N by document frequency). Server clamps to a hard max.
	Limit uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *SuggestRequest) Reset() {
	*x = SuggestRequest{}
	mi := &file_bitmagnet_path_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestRequest) ProtoMessage() {}

func (x *SuggestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bitmagnet_path_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestRequest.ProtoReflect.Descriptor instead.
func (*SuggestRequest) Descriptor() ([]byte, []int) {
	return file_bitmagnet_path_search_proto_rawDescGZIP(), []int{3}
}

func (x *SuggestRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *SuggestRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Suggestion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Suggested path segment (lowercased normalized form).
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// Document frequency: number of torrents whose path-bag contains this segment.
	Score uint64 `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *Suggestion) Reset() {
	*x = Suggestion{}
	mi := &file_bitmagnet_path_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Suggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Suggestion) ProtoMessage() {}

func (x *Suggestion) ProtoReflect() protoreflect.Message {
	mi := &file_bitmagnet_path_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Suggestion.ProtoReflect.Descriptor instead.
func (*Suggestion) Descriptor() ([]byte, []int) {
	return file_bitmagnet_path_search_proto_rawDescGZIP(), []int{4}
}

func (x *Suggestion) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Suggestion) GetScore() uint64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type SuggestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Suggestions []*Suggestion `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
}

func (x *SuggestResponse) Reset() {
	*x = SuggestResponse{}
	mi := &file_bitmagnet_path_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestResponse) ProtoMessage() {}

func (x *SuggestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bitmagnet_path_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestResponse.ProtoReflect.Descriptor instead.
func (*SuggestResponse) Descriptor() ([]byte, []int) {
	return file_bitmagnet_path_search_proto_rawDescGZIP(), []int{5}
}

func (x *SuggestResponse) GetSuggestions() []*Suggestion {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

type PathSearchHealth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status     PathSearchHealth_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=bitmagnet.v1.PathSearchHealth_ServingStatus" json:"status,omitempty"`
	DocCount   uint64                         `protobuf:"varint,2,opt,name=doc_count,json=docCount,proto3" json:"doc_count,omitempty"`
	IndexBytes uint64                         `protobuf:"varint,3,opt,name=index_bytes,json=indexBytes,proto3" json:"index_bytes,omitempty"`
	// Last follow-loop watermark as Unix epoch seconds. Zero when follow is off
	// or has not completed a tick.
	WatermarkEpoch int64 `protobuf:"varint,4,opt,name=watermark_epoch,json=watermarkEpoch,proto3" json:"watermark_epoch,omitempty"`
	Writable       bool  `protobuf:"varint,5,opt,name=writable,proto3" json:"writable,omitempty"`
	// Prefix index loaded and non-empty.
	SuggestReady bool `protobuf:"varint,6,opt,name=suggest_ready,json=suggestReady,proto3" json:"suggest_ready,omitempty"`
	// Number of path segments in the prefix index.
	SuggestEntries uint64 `protobuf:"varint,7,opt,name=suggest_entries,json=suggestEntries,proto3" json:"suggest_entries,omitempty"`
}

func (x *PathSearchHealth) Reset() {
	*x = PathSearchHealth{}
	mi := &file_bitmagnet_path_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathSearchHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathSearchHealth) ProtoMessage() {}

func (x *PathSearchHealth) ProtoReflect() protoreflect.Message {
	mi := &file_bitmagnet_path_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathSearchHealth.ProtoReflect.Descriptor instead.
func (*PathSearchHealth) Descriptor() ([]byte, []int) {
	return file_bitmagnet_path_search_proto_rawDescGZIP(), []int{6}
}

func (x *PathSearchHealth) GetStatus() PathSearchHealth_ServingStatus {
	if x != nil {
		return x.Status
	}
	return PathSearchHealth_SERVING_STATUS_UNKNOWN
}

func (x *PathSearchHealth) GetDocCount() uint64 {
	if x != nil {
		return x.DocCount
	}
	return 0
}

func (x *PathSearchHealth) GetIndexBytes() uint64 {
	if x != nil {
		return x.IndexBytes
	}
	return 0
}

func (x *PathSearchHealth) GetWatermarkEpoch() int64 {
	if x != nil {
		return x.WatermarkEpoch
	}
	return 0
}

func (x *PathSearchHealth) GetWritable() bool {
	if x != nil {
		return x.Writable
	}
	return false
}

func (x *PathSearchHealth) GetSuggestReady() bool {
	if x != nil {
		return x.SuggestReady
	}
	return false
}

func (x *PathSearchHealth) GetSuggestEntries() uint64 {
	if x != nil {
		return x.SuggestEntries
	}
	return 0
}

var File_bitmagnet_path_search_proto protoreflect.FileDescriptor

var file_bitmagnet_path_search_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x62, 0x69, 0x74, 0x6d, 0x61, 0x67, 0x6e, 0x65, 0x74, 0x2f, 0x70, 0x61, 0x74, 0x68,
	0x5f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x62,
	0x69, 0x74, 0x6d, 0x61, 0x67, 0x6e, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x16, 0x62, 0x69, 0x74,
	0x6d, 0x61, 0x67, 0x6e, 0x65, 0x74, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x8d, 0x01, 0x0a, 0x15, 0x50, 0x61, 0x74, 0x68, 0x43, 0x61, 0x6e, 0x64,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x76, 0x65,
	0x72, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x6f,
	0x76, 0x65, 0x72, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x73, 0x6f, 0x72,
	0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x69, 0x74, 0x6d, 0x61, 0x67,
	0x6e, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x52, 0x04, 0x73,
	0x6f, 0x72, 0x74, 0x22, 0x61, 0x0a, 0x0d, 0x50, 0x61, 0x74, 0x68, 0x43, 0x61, 0x6e, 0x64, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x69, 0x6e, 0x66, 0x6f, 0x48, 0x61, 0x73,
	0x68, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x72, 0x74, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x6f, 0x72,
	0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x9c, 0x01, 0x0a, 0x16, 0x50, 0x61, 0x74, 0x68, 0x43,
	0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x62, 0x69, 0x74, 0x6d, 0x61, 0x67, 0x6e, 0x65,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x74, 0x68, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x0a, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x27,
	0x0a, 0x0f, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x73, 0x74, 0x69, 0x6d,
	0x61, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x65, 0x73, 0x74, 0x69,
	0x6d, 0x61, 0x74, 0x65, 0x64, 0x22, 0x3e, 0x0a, 0x0e, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69,
	0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x38, 0x0a, 0x0a, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22,
	0x4d, 0x0a, 0x0f, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0b, 0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62, 0x69, 0x74, 0x6d, 0x61, 0x67,
	0x6e, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x0b, 0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x92,
	0x03, 0x0a, 0x10, 0x50, 0x61, 0x74, 0x68, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x48, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x12, 0x44, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x2c, 0x2e, 0x62, 0x69, 0x74, 0x6d, 0x61, 0x67, 0x6e, 0x65, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x61, 0x74, 0x68, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x48, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x63,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x64, 0x6f,
	0x63, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f,
	0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x77, 0x61, 0x74, 0x65, 0x72,
	0x6d, 0x61, 0x72, 0x6b, 0x5f, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0e, 0x77, 0x61, 0x74, 0x65, 0x72, 0x6d, 0x61, 0x72, 0x6b, 0x45, 0x70, 0x6f, 0x63, 0x68,
	0x12, 0x1a, 0x0a, 0x08, 0x77, 0x72, 0x69, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x77, 0x72, 0x69, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x23, 0x0a, 0x0d,
	0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x79, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0c, 0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x52, 0x65, 0x61, 0x64,
	0x79, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x5f, 0x65, 0x6e, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x73, 0x75, 0x67, 0x67,
	0x65, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x67, 0x0a, 0x0d, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x16, 0x53,
	0x45, 0x52, 0x56, 0x49, 0x4e, 0x47, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x53, 0x45, 0x52, 0x56, 0x49,
	0x4e, 0x47, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x49, 0x4e,
	0x47, 0x10, 0x01, 0x12, 0x1e, 0x0a, 0x1a, 0x53, 0x45, 0x52, 0x56, 0x49, 0x4e, 0x47, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x49, 0x4e,
	0x47, 0x10, 0x02, 0x32, 0x89, 0x02, 0x0a, 0x11, 0x50, 0x61, 0x74, 0x68, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5b, 0x0a, 0x0e, 0x50, 0x61, 0x74,
	0x68, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x23, 0x2e, 0x62, 0x69,
	0x74, 0x6d, 0x61, 0x67, 0x6e, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x74, 0x68, 0x43,
	0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x24, 0x2e, 0x62, 0x69, 0x74, 0x6d, 0x61, 0x67, 0x6e, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x61, 0x74, 0x68, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x07, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73,
	0x74, 0x12, 0x1c, 0x2e, 0x62, 0x69, 0x74, 0x6d, 0x61, 0x67, 0x6e, 0x65, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x62, 0x69, 0x74, 0x6d, 0x61, 0x67, 0x6e, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f,
	0x0a, 0x0b, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x20, 0x2e,
	0x62, 0x69, 0x74, 0x6d, 0x61, 0x67, 0x6e, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x62, 0x69, 0x74, 0x6d, 0x61, 0x67, 0x6e, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x61, 0x74, 0x68, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bitmagnet_path_search_proto_rawDescOnce sync.Once
	file_bitmagnet_path_search_proto_rawDescData = file_bitmagnet_path_search_proto_rawDesc
)

func file_bitmagnet_path_search_proto_rawDescGZIP() []byte {
	file_bitmagnet_path_search_proto_rawDescOnce.Do(func() {
		file_bitmagnet_path_search_proto_rawDescData = protoimpl.X.CompressGZIP(file_bitmagnet_path_search_proto_rawDescData)
	})
	return file_bitmagnet_path_search_proto_rawDescData
}

var file_bitmagnet_path_search_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bitmagnet_path_search_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_bitmagnet_path_search_proto_goTypes = []any{
	(PathSearchHealth_ServingStatus)(0), // 0: bitmagnet.v1.PathSearchHealth.ServingStatus
	(*PathCandidatesRequest)(nil),       // 1: bitmagnet.v1.PathCandidatesRequest
	(*PathCandidate)(nil),               // 2: bitmagnet.v1.PathCandidate
	(*PathCandidatesResponse)(nil),      // 3: bitmagnet.v1.PathCandidatesResponse
	(*SuggestRequest)(nil),              // 4: bitmagnet.v1.SuggestRequest
	(*Suggestion)(nil),                  // 5: bitmagnet.v1.Suggestion
	(*SuggestResponse)(nil),             // 6: bitmagnet.v1.SuggestResponse
	(*PathSearchHealth)(nil),            // 7: bitmagnet.v1.PathSearchHealth
	(*SortBy)(nil),                      // 8: bitmagnet.v1.SortBy
	(*HealthCheckRequest)(nil),          // 9: bitmagnet.v1.HealthCheckRequest
}
var file_bitmagnet_path_search_proto_depIdxs = []int32{
	8, // 0: bitmagnet.v1.PathCandidatesRequest.sort:type_name -> bitmagnet.v1.SortBy
	2, // 1: bitmagnet.v1.PathCandidatesResponse.candidates:type_name -> bitmagnet.v1.PathCandidate
	5, // 2: bitmagnet.v1.SuggestResponse.suggestions:type_name -> bitmagnet.v1.Suggestion
	0, // 3: bitmagnet.v1.PathSearchHealth.status:type_name -> bitmagnet.v1.PathSearchHealth.ServingStatus
	1, // 4: bitmagnet.v1.PathSearchService.PathCandidates:input_type -> bitmagnet.v1.PathCandidatesRequest
	4, // 5: bitmagnet.v1.PathSearchService.Suggest:input_type -> bitmagnet.v1.SuggestRequest
	9, // 6: bitmagnet.v1.PathSearchService.HealthCheck:input_type -> bitmagnet.v1.HealthCheckRequest
	3, // 7: bitmagnet.v1.PathSearchService.PathCandidates:output_type -> bitmagnet.v1.PathCandidatesResponse
	6, // 8: bitmagnet.v1.PathSearchService.Suggest:output_type -> bitmagnet.v1.SuggestResponse
	7, // 9: bitmagnet.v1.PathSearchService.HealthCheck:output_type -> bitmagnet.v1.PathSearchHealth
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_bitmagnet_path_search_proto_init() }
func file_bitmagnet_path_search_proto_init() {
	if File_bitmagnet_path_search_proto != nil {
		return
	}
	file_bitmagnet_search_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bitmagnet_path_search_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bitmagnet_path_search_proto_goTypes,
		DependencyIndexes: file_bitmagnet_path_search_proto_depIdxs,
		EnumInfos:         file_bitmagnet_path_search_proto_enumTypes,
		MessageInfos:      file_bitmagnet_path_search_proto_msgTypes,
	}.Build()
	File_bitmagnet_path_search_proto = out.File
	file_bitmagnet_path_search_proto_rawDesc = nil
	file_bitmagnet_path_search_proto_goTypes = nil
	file_bitmagnet_path_search_proto_depIdxs = nil
}
