// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.28.3
// source: bitmagnet/path_search.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PathSearchService_PathCandidates_FullMethodName = "/bitmagnet.v1.PathSearchService/PathCandidates"
	PathSearchService_HealthCheck_FullMethodName    = "/bitmagnet.v1.PathSearchService/HealthCheck"
)

// PathSearchServiceClient is the client API for PathSearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PathSearchServiceClient interface {
	PathCandidates(ctx context.Context, in *PathCandidatesRequest, opts ...grpc.CallOption) (*PathCandidatesResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*PathSearchHealth, error)
}

type pathSearchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPathSearchServiceClient(cc grpc.ClientConnInterface) PathSearchServiceClient {
	return &pathSearchServiceClient{cc}
}

func (c *pathSearchServiceClient) PathCandidates(ctx context.Context, in *PathCandidatesRequest, opts ...grpc.CallOption) (*PathCandidatesResponse, error) {
	out := new(PathCandidatesResponse)
	err := c.cc.Invoke(ctx, PathSearchService_PathCandidates_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pathSearchServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*PathSearchHealth, error) {
	out := new(PathSearchHealth)
	err := c.cc.Invoke(ctx, PathSearchService_HealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PathSearchServiceServer is the server API for PathSearchService service.
// All implementations must embed UnimplementedPathSearchServiceServer
// for forward compatibility
type PathSearchServiceServer interface {
	PathCandidates(context.Context, *PathCandidatesRequest) (*PathCandidatesResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*PathSearchHealth, error)
	mustEmbedUnimplementedPathSearchServiceServer()
}

// UnimplementedPathSearchServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPathSearchServiceServer struct {
}

func (UnimplementedPathSearchServiceServer) PathCandidates(context.Context, *PathCandidatesRequest) (*PathCandidatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PathCandidates not implemented")
}
func (UnimplementedPathSearchServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*PathSearchHealth, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedPathSearchServiceServer) mustEmbedUnimplementedPathSearchServiceServer() {}

// UnsafePathSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PathSearchServiceServer will
// result in compilation errors.
type UnsafePathSearchServiceServer interface {
	mustEmbedUnimplementedPathSearchServiceServer()
}

func RegisterPathSearchServiceServer(s grpc.ServiceRegistrar, srv PathSearchServiceServer) {
	s.RegisterService(&PathSearchService_ServiceDesc, srv)
}

func _PathSearchService_PathCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PathCandidatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PathSearchServiceServer).PathCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PathSearchService_PathCandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PathSearchServiceServer).PathCandidates(ctx, req.(*PathCandidatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PathSearchService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PathSearchServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PathSearchService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PathSearchServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PathSearchService_ServiceDesc is the grpc.ServiceDesc for PathSearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PathSearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bitmagnet.v1.PathSearchService",
	HandlerType: (*PathSearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PathCandidates",
			Handler:    _PathSearchService_PathCandidates_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _PathSearchService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bitmagnet/path_search.proto",
}
