//! Cross-language parity for the pure `process_torrent_batch` page-to-job
//! boundary generated by the Go implementation.

use std::fs::File;
use std::io::{BufRead, BufReader};
use std::path::Path;

use bitmagnet_queue::{
    BatchPlanner, BatchSelection, ProcessTorrentBatchParams, ProtocolId, QueueJob,
};
use serde::Deserialize;

#[derive(Deserialize)]
struct Fixture {
    id: String,
    subsystem: String,
    input: Input,
    expected: Expected,
}

#[derive(Deserialize)]
struct Input {
    message: ProcessTorrentBatchParams,
    pages: Vec<Vec<ProtocolId>>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct ExpectedJob {
    queue: String,
    payload: String,
    fingerprint: String,
    max_retries: u32,
    priority: i32,
    archival_duration_ns: u64,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Expected {
    queries: Vec<BatchSelection>,
    jobs: Vec<ExpectedJob>,
    max_info_hash: ProtocolId,
    chunk_size: u64,
    done: bool,
}

fn fixtures() -> Vec<Fixture> {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../../testdata/parity/queue/process_torrent_batch_plans.jsonl");
    let file = File::open(&path).unwrap_or_else(|error| panic!("open {}: {error}", path.display()));
    BufReader::new(file)
        .lines()
        .map(|line| line.expect("read fixture line"))
        .filter(|line| !line.trim().is_empty())
        .map(|line| serde_json::from_str(&line).expect("decode batch-plan fixture"))
        .collect()
}

fn assert_job(id: &str, actual: &QueueJob, expected: &ExpectedJob) {
    assert_eq!(actual.queue, expected.queue, "[{id}] queue");
    assert_eq!(actual.payload, expected.payload, "[{id}] payload");
    assert_eq!(
        actual.fingerprint, expected.fingerprint,
        "[{id}] fingerprint"
    );
    assert_eq!(
        actual.max_retries, expected.max_retries,
        "[{id}] max retries"
    );
    assert_eq!(actual.priority, expected.priority, "[{id}] priority");
    assert_eq!(
        actual.archival_duration.as_nanos(),
        u128::from(expected.archival_duration_ns),
        "[{id}] archival duration"
    );
}

#[test]
fn process_torrent_batch_plan_matches_go() {
    let fixtures = fixtures();
    assert_eq!(fixtures.len(), 4, "expected four batch-plan scenarios");

    for fixture in fixtures {
        assert_eq!(fixture.subsystem, "process_torrent_batch_plan");
        assert_eq!(fixture.input.pages.len(), fixture.expected.queries.len());
        let mut planner = BatchPlanner::new(fixture.input.message.clone());
        for (page, query) in fixture.input.pages.iter().zip(&fixture.expected.queries) {
            assert!(planner.should_query(), "[{}] unexpected stop", fixture.id);
            assert_eq!(&planner.selection(), query, "[{}] selection", fixture.id);
            planner
                .add_page(page)
                .unwrap_or_else(|error| panic!("[{}] add page: {error}", fixture.id));
        }

        let plan = planner
            .finalize()
            .unwrap_or_else(|error| panic!("[{}] finalize: {error}", fixture.id));
        assert_eq!(
            plan.max_info_hash, fixture.expected.max_info_hash,
            "[{}] max info hash",
            fixture.id
        );
        assert_eq!(
            plan.chunk_size, fixture.expected.chunk_size,
            "[{}] chunk size",
            fixture.id
        );
        assert_eq!(plan.done, fixture.expected.done, "[{}] done", fixture.id);
        assert_eq!(
            plan.jobs.len(),
            fixture.expected.jobs.len(),
            "[{}] job count",
            fixture.id
        );
        for (actual, expected) in plan.jobs.iter().zip(&fixture.expected.jobs) {
            assert_job(&fixture.id, actual, expected);
        }
    }
}
